### Site Settings ###
title               : Yanqi Xu
description         : >-                               # >- means to ignore newlines until "url:"
                      "Hi this is Yanqi. I am a data journalist. I pore over
                      datasets to discover trends, and tell you what
                      I learned with multimedia in my reporting. 
                      
                      "

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
#repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme


### Build Settings ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                        # Pages with the following paths will be excluded from navbar
  - 404.html
  - index.html
  - blog/tags.html
  - blog/page-:num/index.html


### Author Info ###
author:
  name              : Yanqi Xu
  image             : '/assets/img/profile_pic.jpg'
# behance           : your_username
# dribbble          : your_username
  email             : yanqixu@outlook.com
# facebook          : your_username
  github            : Yanqi-Xu
# gitlab            : your_username
# instagram         : your_username
  linkedin          : yanqi-xu-journalist
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : yanqixu_x
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"


### Posts Permalink ###
permalink: blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock